#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEFAULT_WINDOW_WIDTH				1500
#define DEFAULT_WINDOW_HEIGHT				1000
#define MAX_NUM_OF_STAGE_GAME_OBJECTS		1000
#define RENDER_BACKEND_DEBUG_FONT_TYPE		GLUT_BITMAP_HELVETICA_18

#endif // !CONSTANTS_H
